# -*- coding: utf-8 -*-
"""ejercicio5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14DMT7iVxtMJ2BpT-fmkC9kClY2O5o6CK
"""

import multiprocessing
import random

def calculoPi(n):
    rad = 0
    for _ in range(n):
        a = random.uniform(0, 1)
        b = random.uniform(0, 1)
        if a**2 + b**2 <= 1:
            rad += 1
    return rad

def main():
    total = 1000000  # Total de puntos a generar
    procesos = 3     # Número de procesos
    puntosProceso = total // procesos

    with multiprocessing.Pool(processes=procesos) as pool:
        res = pool.map(calculoPi, [puntosProceso] * procesos)

    radTotal = sum(res)
    piGenerado = (radTotal / total) * 4

    print(f"Valor de π: {piGenerado}")

if __name__ == "__main__":
    main()